//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ProductsWeb {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto_BE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Producto_BE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BorradoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((object.ReferenceEquals(this.PrecioField, value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Borrado {
            get {
                return this.BorradoField;
            }
            set {
                if ((object.ReferenceEquals(this.BorradoField, value) != true)) {
                    this.BorradoField = value;
                    this.RaisePropertyChanged("Borrado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductsWeb.ProductsWebServicesSoap")]
    public interface ProductsWebServicesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListProductsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListProducts", ReplyAction="*")]
        WebApp.ProductsWeb.ListProductsResponse ListProducts(WebApp.ProductsWeb.ListProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApp.ProductsWeb.ListProductsResponse> ListProductsAsync(WebApp.ProductsWeb.ListProductsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListProducts", Namespace="http://tempuri.org/", Order=0)]
        public WebApp.ProductsWeb.ListProductsRequestBody Body;
        
        public ListProductsRequest() {
        }
        
        public ListProductsRequest(WebApp.ProductsWeb.ListProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListProductsRequestBody {
        
        public ListProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApp.ProductsWeb.ListProductsResponseBody Body;
        
        public ListProductsResponse() {
        }
        
        public ListProductsResponse(WebApp.ProductsWeb.ListProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApp.ProductsWeb.Producto_BE[] ListProductsResult;
        
        public ListProductsResponseBody() {
        }
        
        public ListProductsResponseBody(WebApp.ProductsWeb.Producto_BE[] ListProductsResult) {
            this.ListProductsResult = ListProductsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductsWebServicesSoapChannel : WebApp.ProductsWeb.ProductsWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductsWebServicesSoapClient : System.ServiceModel.ClientBase<WebApp.ProductsWeb.ProductsWebServicesSoap>, WebApp.ProductsWeb.ProductsWebServicesSoap {
        
        public ProductsWebServicesSoapClient() {
        }
        
        public ProductsWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductsWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.ProductsWeb.ListProductsResponse WebApp.ProductsWeb.ProductsWebServicesSoap.ListProducts(WebApp.ProductsWeb.ListProductsRequest request) {
            return base.Channel.ListProducts(request);
        }
        
        public WebApp.ProductsWeb.Producto_BE[] ListProducts() {
            WebApp.ProductsWeb.ListProductsRequest inValue = new WebApp.ProductsWeb.ListProductsRequest();
            inValue.Body = new WebApp.ProductsWeb.ListProductsRequestBody();
            WebApp.ProductsWeb.ListProductsResponse retVal = ((WebApp.ProductsWeb.ProductsWebServicesSoap)(this)).ListProducts(inValue);
            return retVal.Body.ListProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApp.ProductsWeb.ListProductsResponse> WebApp.ProductsWeb.ProductsWebServicesSoap.ListProductsAsync(WebApp.ProductsWeb.ListProductsRequest request) {
            return base.Channel.ListProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApp.ProductsWeb.ListProductsResponse> ListProductsAsync() {
            WebApp.ProductsWeb.ListProductsRequest inValue = new WebApp.ProductsWeb.ListProductsRequest();
            inValue.Body = new WebApp.ProductsWeb.ListProductsRequestBody();
            return ((WebApp.ProductsWeb.ProductsWebServicesSoap)(this)).ListProductsAsync(inValue);
        }
    }
}
